language: cpp
dist: bionic
addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - ninja-build
      - python-pip
      
script:
  - pip install cmake
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../external/LibreUCpp/toolchain-arm-none-eabi.cmake ..
  - cmake --build .
  
