language: cpp
dist: bionic
addons:
  apt:
    packages:
      - python3-pip
      - ninja-build
      
script:
  - pip3 install --user cmake
  - wget "https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2?revision=c34d758a-be0c-476e-a2de-af8c6e16a8a2?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,8-2019-q3-update" -O gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2
  - tar xjf gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2
  - export PATH=gcc-arm-none-eabi-8-2019-q3-update/bin:$PATH
  - which arm-none-eabi-gcc
  - arm-none-eabi-gcc --version
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../external/LibreUCpp/toolchain-arm-none-eabi.cmake ..
  - cmake --build .
  
