language: cpp
dist: bionic
addons:
  apt:
    packages:
      - python3-pip
      - ninja-build
      - gcc-arm-none-eabi
      
script:
  - pip3 install --user cmake
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=../external/LibreUCpp/toolchain-arm-none-eabi.cmake ..
  - cmake --build .
  
